import Head from "next/head";
import styles from "styles/Home.module.css";
import { AppStateProvider } from "libs/state/AppState";
import { ApiKeyFormModal } from "componets/modal/ApiKeyFormModal";
import { ApiKeyStateProvider } from "libs/state/ApiKeyState";
import { Main } from "componets/Main/main";

const Home = () => {
  return (
    <AppStateProvider>
      <ApiKeyStateProvider>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          {/* <main className={styles.main}> */}
          <Main />
        </div>
        <ApiKeyFormModal />
      </ApiKeyStateProvider>
    </AppStateProvider>
  );
};

// export const getStaticProps: GetStaticProps = async () => {
//   const data = await getPrefectures();
//   return {
//     props: {
//       data: data as PrefecturesResponse,
//     },
//   };
// };

export default Home;
