import type { GetStaticProps } from "next";
import Head from "next/head";
import styles from "styles/Home.module.css";
import { Checklists } from "componets/checklists/checklists";
import { getPrefectures } from "libs/get-prefectures";
import { PrefecturesResponse } from "model/prefectures";
import { ArtificialTransitiveGraph } from "componets/artificial-transitive-graph/artificial-transitive-graph";

const Home = ({ data }: { data: PrefecturesResponse }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <main className={styles.main}> */}
      <main>
        <Checklists data={data} />
        <ArtificialTransitiveGraph />
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const data = await getPrefectures();
  return {
    props: {
      data: data as PrefecturesResponse,
    },
  };
};

export default Home;
